version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: "10s"
      retries: 10
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: ruby server.rb
    tty: true
    container_name: ruby-container
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
